import sys

with open(r'c:\Users\julia\Desktop\cout de revient\index.html', 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_lines = lines[:2271]

new_lines.extend(r"""                 <!-- Reception View -->
                 <div id="haccpViewReception" class="haccp-view" style="display:none;">
                    <div class="mgmt-glass-card" style="padding: 2.5rem;">
                       <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:2rem;">
                          <div>
                             <h3 style="margin:0; font-family:var(--font-display); font-size:1.4rem; color:var(--primary);">🚚 Contrôles à la Réception</h3>
                             <p style="font-size:0.85rem; color:var(--text-muted); margin:5px 0 0 0;">Vérification des marchandises à l'arrivée (température, hygiène).</p>
                          </div>
                          <button class="btn btn-primary" onclick="showAddReceptionModal()" style="border-radius:12px; padding:0.8rem 1.6rem; font-weight:700;">✚ Nouveau Contrôle</button>
                       </div>
                       <div class="table-responsive">
                          <table class="premium-table">
                             <thead>
                                <tr>
                                   <th>Date</th>
                                   <th>Fournisseur</th>
                                   <th>Temp. Camion</th>
                                   <th>État Hygiène</th>
                                   <th>Statut</th>
                                   <th style="text-align:right;">Action</th>
                                </tr>
                             </thead>
                             <tbody id="receptionLogsBody"></tbody>
                          </table>
                       </div>
                    </div>
                 </div>

                 <!-- Allergens View -->
                 <div id="haccpViewAllergens" class="haccp-view" style="display:none;">
                    <div class="mgmt-glass-card" style="padding: 2.5rem;">
                       <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:2rem;">
                          <div>
                             <h3 style="margin:0; font-family:var(--font-display); font-size:1.4rem; color:var(--primary);">⚖️ Registre des Allergènes</h3>
                             <p style="font-size:0.85rem; color:var(--text-muted); margin:5px 0 0 0;">Conformité INCO - Informations obligatoires pour les consommateurs.</p>
                          </div>
                          <button class="btn btn-primary" onclick="window.print()" style="border-radius:12px; padding:0.8rem 1.6rem; font-weight:700;">🖨️ Imprimer Registre</button>
                       </div>
                       <div class="table-responsive">
                          <table class="allergen-matrix-premium" id="allergenMatrixTable" style="width:100%; border-collapse:collapse;">
                             <!-- Generated by JS -->
                          </table>
                       </div>
                       <div style="margin-top:2.5rem; display:flex; gap:2rem; justify-content:center; padding:1.5rem; background:rgba(99, 102, 241, 0.03); border-radius:15px; border:1px solid rgba(99, 102, 241, 0.05);">
                          <div style="display:flex; align-items:center; gap:0.6rem; font-size:0.85rem; color:var(--text-muted); font-weight:600;">
                             <span style="width:10px; height:10px; background:#ef4444; border-radius:50%;"></span> Présent
                          </div>
                          <div style="display:flex; align-items:center; gap:0.6rem; font-size:0.85rem; color:var(--text-muted); font-weight:600;">
                             <span style="width:10px; height:10px; background:rgba(99,102,241,0.1); border-radius:50%;"></span> Absent
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
           </main>
        </div>
    </section>
""".splitlines(keepends=True))

new_lines.extend(lines[2408:])

with open(r'c:\Users\julia\Desktop\cout de revient\index.html', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)
